In [1]:
import numpy as np

In [2]:
a=[3,4,5,6]
type(a)

list

In [3]:
np.array(a)

array([3, 4, 5, 6])

In [4]:
type(np.array(a))

numpy.ndarray

In [5]:
b=[3.,4,5,6.0]
np.array(b)

array([3., 4., 5., 6.])

In [6]:
v=np.array([[1,2,3],[3,4,5]])

In [7]:
v

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
v[0][1]

2

In [9]:
v.shape

(2, 3)

In [10]:
np.array([4,5,6,7])

array([4, 5, 6, 7])

In [11]:
np.array([4,5,6,7],ndmin=25)

array([[[[[[[[[[[[[[[[[[[[[[[[[4, 5, 6, 7]]]]]]]]]]]]]]]]]]]]]]]]])

In [12]:
np.array([4,5,6,7],dtype=complex)

array([4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [13]:
p=np.array([[1,2,3],[3,4]])

In [14]:
p

array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [15]:
n=np.array([(3,4),(5,6)],dtype=[('a','<i4'),('b','<i2')])

In [16]:
n

array([(3, 4), (5, 6)], dtype=[('a', '<i4'), ('b', '<i2')])

In [17]:
n[0]

(3, 4)

In [18]:
n[1]

(5, 6)

In [19]:
type(n[0][0])

numpy.int32

In [20]:
[0]

[0]

In [21]:
type(n[0][1])

numpy.int16

In [22]:
m=np.mat([1,2,3,4])
m

matrix([[1, 2, 3, 4]])

In [23]:
type(np.mat([1,2,3,4]))

numpy.matrixlib.defmatrix.matrix

In [24]:
np.array(m)

array([[1, 2, 3, 4]])

In [25]:
np.asanyarray([5,6,7,78])

array([ 5,  6,  7, 78])

In [26]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [27]:
a=np.array([4,5,6,7,8])

In [28]:
b=a

In [29]:
a

array([4, 5, 6, 7, 8])

In [30]:
b[0]=335

In [31]:
b

array([335,   5,   6,   7,   8])

In [32]:
c=np.copy(a)

In [33]:
c

array([335,   5,   6,   7,   8])

In [34]:
a

array([335,   5,   6,   7,   8])

In [35]:
c[0]=343

In [36]:
c

array([343,   5,   6,   7,   8])

In [37]:
a

array([335,   5,   6,   7,   8])

In [38]:
a[0]=6565

In [39]:
a

array([6565,    5,    6,    7,    8])

In [40]:
c

array([343,   5,   6,   7,   8])

In [41]:
np.fromfunction (lambda x,y:x==y,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [42]:
np.fromfunction(lambda x,y:x-y*6,(3,4))

array([[  0.,  -6., -12., -18.],
       [  1.,  -5., -11., -17.],
       [  2.,  -4., -10., -16.]])

In [43]:
np.fromstring('6,7',dtype=int,sep=',')

array([6, 7])

In [44]:
a=[[3,4,5],[6.7,8],[6,7,9]]

In [45]:
n=np.array(a)

In [46]:
n

array([list([3, 4, 5]), list([6.7, 8]), list([6, 7, 9])], dtype=object)

In [47]:
n=np.array(a,ndmin=10)

In [48]:
n=np.array(a)

In [49]:
n

array([list([3, 4, 5]), list([6.7, 8]), list([6, 7, 9])], dtype=object)

In [50]:
n.ndim

1

In [51]:
n.size

3

In [52]:
n.shape

(3,)

In [53]:
m=np.array([])

In [54]:
n.dtype

dtype('O')

In [55]:
n=np.arange(2.5,9.87,.5)

In [56]:
list(n)

[2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]

In [57]:
np.linspace(3,7,200)

array([3.        , 3.0201005 , 3.04020101, 3.06030151, 3.08040201,
       3.10050251, 3.12060302, 3.14070352, 3.16080402, 3.18090452,
       3.20100503, 3.22110553, 3.24120603, 3.26130653, 3.28140704,
       3.30150754, 3.32160804, 3.34170854, 3.36180905, 3.38190955,
       3.40201005, 3.42211055, 3.44221106, 3.46231156, 3.48241206,
       3.50251256, 3.52261307, 3.54271357, 3.56281407, 3.58291457,
       3.60301508, 3.62311558, 3.64321608, 3.66331658, 3.68341709,
       3.70351759, 3.72361809, 3.74371859, 3.7638191 , 3.7839196 ,
       3.8040201 , 3.8241206 , 3.84422111, 3.86432161, 3.88442211,
       3.90452261, 3.92462312, 3.94472362, 3.96482412, 3.98492462,
       4.00502513, 4.02512563, 4.04522613, 4.06532663, 4.08542714,
       4.10552764, 4.12562814, 4.14572864, 4.16582915, 4.18592965,
       4.20603015, 4.22613065, 4.24623116, 4.26633166, 4.28643216,
       4.30653266, 4.32663317, 4.34673367, 4.36683417, 4.38693467,
       4.40703518, 4.42713568, 4.44723618, 4.46733668, 4.48743

In [58]:
np.linspace(3,7.9)

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9])

In [59]:
np.linspace(3.,7.9,5,endpoint=False,retstep=True)


(array([3.  , 3.98, 4.96, 5.94, 6.92]), 0.9800000000000001)

In [60]:
np.linspace(3,7.9, axis=0)

TypeError: linspace() got an unexpected keyword argument 'axis'

In [ ]:
np.zeros((3,5,6,2))

In [61]:
 np.ones((2,3,4))+1

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [62]:
np.empty((4,5))

array([[6.65000638e-282, 0.00000000e+000, 1.41537862e+161,
        5.22182633e+180, 7.33952596e+223],
       [4.83245960e+276, 1.05089721e-153, 1.05089708e-153,
        6.12743486e-154, 4.02456140e-066],
       [2.99937164e-067, 1.03080218e+136, 6.01347002e-154,
        3.64464654e-086, 3.64464654e-086],
       [1.81154498e-152, 1.20336039e+132, 1.05089708e-153,
        5.46453735e-095, 6.01347002e-154]])

In [63]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.logspace(5.6,7.8,8)

array([  398107.1705535 ,   820891.41596382,  1692666.61503788,
        3490254.87895958,  7196856.73001151, 14839817.88967563,
       30599496.87207196, 63095734.4480193 ])

In [65]:
m=np.random.rand(4,5)

In [66]:
m

array([[0.32839613, 0.2960134 , 0.21414937, 0.91734834, 0.3550305 ],
       [0.3995174 , 0.91444202, 0.58954793, 0.32959859, 0.86363317],
       [0.00385795, 0.22698598, 0.415937  , 0.58739015, 0.94171998],
       [0.03714592, 0.8537816 , 0.85970558, 0.25111772, 0.37843565]])

In [67]:
m.reshape(10,2)

array([[0.32839613, 0.2960134 ],
       [0.21414937, 0.91734834],
       [0.3550305 , 0.3995174 ],
       [0.91444202, 0.58954793],
       [0.32959859, 0.86363317],
       [0.00385795, 0.22698598],
       [0.415937  , 0.58739015],
       [0.94171998, 0.03714592],
       [0.8537816 , 0.85970558],
       [0.25111772, 0.37843565]])

In [68]:
m.reshape(20,1)

array([[0.32839613],
       [0.2960134 ],
       [0.21414937],
       [0.91734834],
       [0.3550305 ],
       [0.3995174 ],
       [0.91444202],
       [0.58954793],
       [0.32959859],
       [0.86363317],
       [0.00385795],
       [0.22698598],
       [0.415937  ],
       [0.58739015],
       [0.94171998],
       [0.03714592],
       [0.8537816 ],
       [0.85970558],
       [0.25111772],
       [0.37843565]])

In [69]:
m.reshape(5,4)

array([[0.32839613, 0.2960134 , 0.21414937, 0.91734834],
       [0.3550305 , 0.3995174 , 0.91444202, 0.58954793],
       [0.32959859, 0.86363317, 0.00385795, 0.22698598],
       [0.415937  , 0.58739015, 0.94171998, 0.03714592],
       [0.8537816 , 0.85970558, 0.25111772, 0.37843565]])

In [70]:
m.reshape(10,-254446)

array([[0.32839613, 0.2960134 ],
       [0.21414937, 0.91734834],
       [0.3550305 , 0.3995174 ],
       [0.91444202, 0.58954793],
       [0.32959859, 0.86363317],
       [0.00385795, 0.22698598],
       [0.415937  , 0.58739015],
       [0.94171998, 0.03714592],
       [0.8537816 , 0.85970558],
       [0.25111772, 0.37843565]])

In [71]:
m.reshape(-4345,10)

array([[0.32839613, 0.2960134 , 0.21414937, 0.91734834, 0.3550305 ,
        0.3995174 , 0.91444202, 0.58954793, 0.32959859, 0.86363317],
       [0.00385795, 0.22698598, 0.415937  , 0.58739015, 0.94171998,
        0.03714592, 0.8537816 , 0.85970558, 0.25111772, 0.37843565]])

In [72]:
m.reshape(3,10)

ValueError: cannot reshape array of size 20 into shape (3,10)

In [73]:
np.random

<module 'numpy.random' from 'C:\\Users\\Manish\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [74]:
m=np.random.rand(4,5)

In [75]:
m

array([[0.2664904 , 0.82158713, 0.55910662, 0.68280469, 0.98553582],
       [0.70685211, 0.95202459, 0.37976347, 0.76612988, 0.17263972],
       [0.34056316, 0.28087978, 0.91585623, 0.33602185, 0.80046796],
       [0.78026335, 0.94395158, 0.84579916, 0.90077027, 0.48719502]])

In [76]:
np.random.randn(5,6)

array([[ 1.75622878,  1.21263249,  0.57126793, -2.38998043, -1.52050208,
        -0.35075147],
       [ 1.45348938, -0.44561551, -1.48640338, -1.23732648, -1.52264927,
         1.27510895],
       [ 0.40048471,  0.74107965, -0.13976816, -0.36110797,  0.08040985,
        -0.15148557],
       [-0.39032877,  0.65377271, -0.41375893,  0.1926875 ,  1.03506977,
        -0.35332119],
       [ 1.33318872, -1.00070346, -0.68538649, -1.39676542, -0.33566189,
         1.08702466]])

In [77]:
a=np.random.randint(3,8,(5,6 ))

In [78]:
a

array([[5, 4, 3, 6, 3, 5],
       [6, 3, 4, 3, 4, 5],
       [4, 7, 3, 4, 7, 4],
       [6, 6, 4, 7, 5, 3],
       [6, 6, 7, 4, 6, 5]])

In [79]:
a[0:2,0:2]

array([[5, 4],
       [6, 3]])

In [80]:
a[a>5]

array([6, 6, 7, 7, 6, 6, 7, 6, 6, 7, 6])

In [81]:
a[0][0]=90

In [82]:
a

array([[90,  4,  3,  6,  3,  5],
       [ 6,  3,  4,  3,  4,  5],
       [ 4,  7,  3,  4,  7,  4],
       [ 6,  6,  4,  7,  5,  3],
       [ 6,  6,  7,  4,  6,  5]])

In [114]:
m=np.array([[3,4,5],[5,6,7]])

In [115]:
m

array([[3, 4, 5],
       [5, 6, 7]])

In [116]:
n=np.array([[67,4,5],[5,0,5]])

In [117]:
n

array([[67,  4,  5],
       [ 5,  0,  5]])

In [118]:
m+n

array([[70,  8, 10],
       [10,  6, 12]])

In [119]:
m-n

array([[-64,   0,   0],
       [  0,   6,   2]])

In [120]:
n

array([[67,  4,  5],
       [ 5,  0,  5]])

In [121]:
m*n

array([[201,  16,  25],
       [ 25,   0,  35]])

In [122]:
m1=np.array([[0,1],[2,3]])

In [123]:
m1

array([[0, 1],
       [2, 3]])

In [124]:
m2=np.array([[2,3],[1,8]])

In [125]:
m2

array([[2, 3],
       [1, 8]])

In [126]:
m1*m2

array([[ 0,  3],
       [ 2, 24]])

In [127]:
m1@m2

array([[ 1,  8],
       [ 7, 30]])

In [128]:
m1**2

array([[0, 1],
       [4, 9]], dtype=int32)

In [129]:
pow(m1,2)

array([[0, 1],
       [4, 9]], dtype=int32)

In [130]:
m=np.zeros((3,4))

In [131]:
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [132]:
m+2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [133]:
n1=np.array([1,3,4,2])

In [134]:
n1

array([1, 3, 4, 2])

In [135]:
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
m+n1

array([[1., 3., 4., 2.],
       [1., 3., 4., 2.],
       [1., 3., 4., 2.]])

In [150]:
n2=np.array([[3,4,5]]).T

In [151]:
n2

array([[3],
       [4],
       [5]])

In [152]:
m+n2

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [156]:
m=np.random.rand(4,5).reshape(10,2)

In [157]:
m

array([[0.38541192, 0.36781813],
       [0.03053957, 0.41685613],
       [0.78286887, 0.22316538],
       [0.70725898, 0.20023721],
       [0.7644141 , 0.30639959],
       [0.0306131 , 0.72790205],
       [0.8313427 , 0.24255091],
       [0.82236086, 0.35357163],
       [0.13333455, 0.49988894],
       [0.60127021, 0.85026094]])

In [158]:
m1=np.random.rand(4,5).reshape(10,2)

In [159]:
m1

array([[0.40002457, 0.83169047],
       [0.61225487, 0.56126217],
       [0.99848285, 0.39905766],
       [0.57492161, 0.27384753],
       [0.22353613, 0.48257267],
       [0.81766756, 0.2151742 ],
       [0.25052653, 0.7033087 ],
       [0.43556122, 0.98941791],
       [0.2216396 , 0.47057474],
       [0.64391427, 0.86431627]])

In [160]:
np.sqrt(m1)

array([[0.63247496, 0.91197065],
       [0.78246717, 0.74917432],
       [0.99924114, 0.6317101 ],
       [0.75823586, 0.52330443],
       [0.47279608, 0.69467451],
       [0.90424972, 0.46386873],
       [0.50052626, 0.83863502],
       [0.65997062, 0.99469488],
       [0.47078615, 0.6859845 ],
       [0.80244269, 0.92968611]])

In [161]:
np.exp(m1)

array([[1.49186136, 2.29719882],
       [1.84458601, 1.75288353],
       [2.71416092, 1.49041955],
       [1.77699123, 1.31501428],
       [1.25049082, 1.62023739],
       [2.2652102 , 1.2400779 ],
       [1.28470168, 2.02042664],
       [1.54583037, 2.68966838],
       [1.24812148, 1.60091403],
       [1.90391877, 2.37338278]])

In [165]:
np.log10(m1)

array([[-3.97913328e-01, -8.00382726e-02],
       [-2.13067754e-01, -2.50834232e-01],
       [-6.59389898e-04, -3.98964353e-01],
       [-2.40391364e-01, -5.62491176e-01],
       [-6.50652270e-01, -3.16437274e-01],
       [-8.74232321e-02, -6.67209807e-01],
       [-6.01146273e-01, -1.52854012e-01],
       [-3.60950792e-01, -4.62023298e-03],
       [-6.54352637e-01, -3.27371393e-01],
       [-1.91171948e-01, -6.33273113e-02]])

In [166]:
m1

array([[0.40002457, 0.83169047],
       [0.61225487, 0.56126217],
       [0.99848285, 0.39905766],
       [0.57492161, 0.27384753],
       [0.22353613, 0.48257267],
       [0.81766756, 0.2151742 ],
       [0.25052653, 0.7033087 ],
       [0.43556122, 0.98941791],
       [0.2216396 , 0.47057474],
       [0.64391427, 0.86431627]])

In [167]:
m

array([[0.38541192, 0.36781813],
       [0.03053957, 0.41685613],
       [0.78286887, 0.22316538],
       [0.70725898, 0.20023721],
       [0.7644141 , 0.30639959],
       [0.0306131 , 0.72790205],
       [0.8313427 , 0.24255091],
       [0.82236086, 0.35357163],
       [0.13333455, 0.49988894],
       [0.60127021, 0.85026094]])

In [169]:
np.fmod(m,m1)

array([[0.38541192, 0.36781813],
       [0.03053957, 0.41685613],
       [0.78286887, 0.22316538],
       [0.13233737, 0.20023721],
       [0.09380571, 0.30639959],
       [0.0306131 , 0.08237946],
       [0.0797631 , 0.24255091],
       [0.38679964, 0.35357163],
       [0.13333455, 0.0293142 ],
       [0.60127021, 0.85026094]])

In [173]:
n=np.array([[3,4,5],[1,2,3],[3,6,7]],ndmin=10)

In [174]:
n

array([[[[[[[[[[3, 4, 5],
               [1, 2, 3],
               [3, 6, 7]]]]]]]]]])

In [175]:
n.shape

(1, 1, 1, 1, 1, 1, 1, 1, 3, 3)

In [177]:
n1=np.array([[1,2,3],[6,7,8],[3,4,5]])

In [182]:
n1.reshape(3,1,3)

array([[[1, 2, 3]],

       [[6, 7, 8]],

       [[3, 4, 5]]])

In [183]:
n1.shape

(3, 3)

In [188]:
n1.ndim

2

In [190]:
np.linspace(3,7,45)

array([3.        , 3.09090909, 3.18181818, 3.27272727, 3.36363636,
       3.45454545, 3.54545455, 3.63636364, 3.72727273, 3.81818182,
       3.90909091, 4.        , 4.09090909, 4.18181818, 4.27272727,
       4.36363636, 4.45454545, 4.54545455, 4.63636364, 4.72727273,
       4.81818182, 4.90909091, 5.        , 5.09090909, 5.18181818,
       5.27272727, 5.36363636, 5.45454545, 5.54545455, 5.63636364,
       5.72727273, 5.81818182, 5.90909091, 6.        , 6.09090909,
       6.18181818, 6.27272727, 6.36363636, 6.45454545, 6.54545455,
       6.63636364, 6.72727273, 6.81818182, 6.90909091, 7.        ])